backend:
  name: github
  repo: C3PablO/gatsby-starter-netlify-cms

media_folder: static/img
public_folder: /img

collections:
  - label: "Secciones"
    name: "sections"
    files:
      - file: "src/sections/curriculum/index.md"
        label: "Curriculum"
        name: "curriculum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "curriculum-section"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "work"
    label: "Trabajos"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "work-page"}
      - {label: Titulo, name: title, widget: string}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Orden", name: "order", widget: "number", min: 0 }
      - {label: "Color", name: "color", widget: "string" }
      - {label: Preview, name: image, widget: image}
      - {label: Texto, name: body, widget: markdown }
      - {label: Imagenes, name: images, widget: list, fields: [{label: Image, name: image, widget: image}]}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Image, name: image, widget: image}