backend:
  name: git-gateway
  repo: C3PablO/zaidaescobar
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "work"
    label: "Trabajos"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "work-page"}
      - {label: Titulo, name: title, widget: string}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Orden", name: "order", widget: "number", min: 0 }
      - {label: "Color", name: "color", widget: "color" }
      - {label: Preview, name: image, widget: image}
      - {label: Texto, name: body, widget: markdown }
      - {label: Imagenes, name: images, widget: list, fields: [{label: Image, name: image, widget: image}]}
      - {label: "Tags", name: "tags", widget: "list"}
  
  - label: "Secciones"
    name: "sections"
    files:
      - file: "src/sections/about/index.md"
        label: "Sobre mi"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-section"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Image, name: image, widget: image}

  - name: "pages"
    label: "Detalles"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}